GET http://localhost:{{port}}/api/search?artist=johnny%20booth&title=asymmetrical
Accept: application/json

> {%

client.test("Song search returns a 200 for a proper search query", function () {
     client.assert(response.status === 200, "Response status is not 200");
 })
%}

###

// Search track should return 400 => BAD_REQUEST for missing query

GET http://localhost:{{port}}/api/search
Accept: application/json

> {% client.test("Song search returns 400 for a bad request", function() {
    client.assert(response.status === 400, "Response status is not 400");

    client.assert(response.body.error.name === "BAD_REQUEST");
    client.assert(response.body.error.message === "Problem with property \"title\": it does not exist in received object {}" );
}) %}

###


